/**
 * @file File.h
 * @author MeerkatBoss (solodovnikov.ia@phystech.su)
 *
 * @brief Data structures for indexing and tagging files
 *
 * @version 0.1
 * @date 2024-09-04
 *
 * @copyright Copyright MeerkatBoss (c) 2024
 */
#ifndef __FILES_FILE_H
#define __FILES_FILE_H

#include <stddef.h>
#include <stdint.h>
#include <time.h>

#include "Common/List.h"
#include "Files/Error.h"

/**
 * @brief Description of action that should be performed on file
 */
enum FileAction {
  FACT_COPY,    /*!< File should be copied to destination directory */
  FACT_MOVE,    /*!< File should be moved to destination directory */
  FACT_IGNORE,  /*!< File should be skipped */
  FACT_DELETE   /*!< File should be deleted from source directory */
};

typedef enum FileAction file_action_t;

/**
 * @brief Description of pending changes to file
 */
typedef struct {
  file_action_t action;
} FileChanges;

/**
 * @brief Description of file found in source directory
 */
typedef struct {
  LinkedListNode as_node;

  char* path;                 /*!< Full path to file */
  time_t real_timestamp;      /*!< File creation date */
  time_t override_timestamp;  /*!< Timestamp used for file name */

  unsigned tag_count;         /*!< Number of tags added to file */
  char* tags[FILE_MAX_TAGS];  /*!< File tags */

  FileChanges changes;  /*!< Changes to be applied */
} IndexedFile;

/**
 * @brief Calendar date override to apply to a file's `override_timestamp`
 *
 * `offset_*` fields are additive, applied to the file's own calendar date
 * (from `real_timestamp`). `year`/`month`/`day` are absolute replacements
 * applied afterward, with `0` meaning "not given" (left as computed by
 * the offset). Both kinds can be given together, though CLI parsing only
 * ever produces one or the other.
 */
typedef struct {
  int offset_year;   /*!< Additive year offset */
  int offset_month;  /*!< Additive month offset */
  int offset_day;    /*!< Additive day offset */
  unsigned year;      /*!< Absolute year, 0 if not given */
  unsigned month;     /*!< Absolute month (1-12), 0 if not given */
  unsigned day;       /*!< Absolute day of month, 0 if not given */
} TimestampOverride;

/**
 * @brief Initialize file from path
 *
 * @return FERR_NONE on success
 *         FERR_INVALID_VALUE on invalid path,
 *         FERR_ACCESS_DENIED if path cannot be accessed
 */
file_error_t file_init(IndexedFile* file, const char* path);

/**
 * @brief Recompute `file->override_timestamp` from `real_timestamp` by
 * applying `override`
 *
 * @note Time of day (hour/minute/second) is always preserved from
 * `real_timestamp`; only the calendar date changes.
 */
void file_apply_timestamp_override(
  IndexedFile* file,
  const TimestampOverride* override
);

enum {
  FILE_DATE_BUFSIZE = 11 /*!< Length of "YYYY-MM-DD\0" */
};

/**
 * @brief Format `file->override_timestamp` as "YYYY-MM-DD" (UTC)
 */
void file_format_date(
  const IndexedFile* file,  /*!< [in]  Target file */
  char* buf,                /*!< [out] Buffer of at least FILE_DATE_BUFSIZE */
  size_t buf_size           /*!< [in]  Size of `buf` */
);

/**
 * @brief Truncate a UTC timestamp to midnight of its calendar day
 *
 * @note Used to compare timestamps by calendar date alone, e.g. for
 * per-date file numbering.
 */
time_t file_truncate_to_day(time_t timestamp);

/**
 * @brief Components parsed back out of a name generated by
 * `file_generate_name()`
 */
typedef struct {
  time_t date;                /*!< Midnight UTC of the encoded date */
  unsigned short index;       /*!< Parsed numeric index */
  char* tags[FILE_MAX_TAGS];  /*!< Allocated tag strings */
  size_t tag_count;           /*!< Number of tags */
  char* extension;            /*!< Allocated, "" if filename has none */
} OrganizedName;

/**
 * @brief Parse a filename of the form
 * `YYYY-MM-DD_XXX_tag1_tag2.extension` back into its components
 *
 * @return FERR_NONE on success,
 *         FERR_INVALID_VALUE if `filename` does not match the format
 *
 * @note Intended for filenames already found in a directory (e.g. by
 * `file_index_scan_target()`) -- mismatches are expected to be skipped
 * by the caller rather than treated as fatal.
 */
file_error_t file_parse_organized_name(
  const char* filename,
  OrganizedName* out
);

/**
 * @brief Deallocate resources held by an `OrganizedName`
 */
void file_organized_name_cleanup(OrganizedName* name);

/**
 * @brief Deallocate resources used by IndexedFile
 */
void file_cleanup(IndexedFile* file);

/**
 * @brief Validate tag string format
 *
 * @return 0 if tag is invalid, nonzero if it is valid
 *
 * @note Tags can only contain lowercase latin letters and dash symbol '-'
 */
int file_tag_is_valid(const char* tag);

/**
 * @brief Add tag to list of file tags. Duplicate tags are ignored.
 *
 * @return FERR_NONE on success,
 *         FERR_INVALID_VALUE if tag contains invalid characters,
 *         FERR_INVALID_OPERATION if number of tags exceeds FILE_MAX_TAGS
 *
 * @note Tags can only contain lowercase latin letters and dash symbol '-'
 */
file_error_t file_add_tag(IndexedFile* file, const char* tag);

/**
 * @brief Get unique sorted tags from file
 * 
 * @return Number of unique tags. If this exceeds `unique_count`,
 *         returned list of tags is truncated to fit in buffer.
 */
size_t file_get_unique_tags(
  const IndexedFile* file,  /*!< [in]  Target file */
  size_t unique_count,      /*!< [in]  Max unique tags to store in buffer */
  const char* unique_tags[] /*!< [out] Buffer for tags, ignored if `NULL` */
);

/**
 * @brief Remove provided tag from file
 * 
 * @return Number of removed tags
 *
 * @note This operation does not preserve order of tags
 */
int file_remove_tag(IndexedFile* file, const char* tag);

/**
 * @brief Remove all tags from file
 */
void file_clear_tags(IndexedFile* file);

/**
 * @brief Generate new name for file based on timestamp, index and tags
 *
 * @note
 * File name has the following format:
 * `YYYY-MM-DD_XXX_underscore_separated_tags.extension`
 * Tags are sorted alphabetically and duplicate tags are removed.
 *
 * @return Length of generated name. If this length exceeds buffer length,
 *         the name is truncated to fit.
 */
unsigned long file_generate_name(
  const IndexedFile* file,    /*!< [in]  Target file */
  unsigned short file_index,  /*!< [in]  Index of file in list */
  unsigned long buf_length,   /*!< [in]  Length of `name_buf` */
  char* name_buf              /*!< [out] Output buffer for file name */
);

#endif /* File.h */
